//! crates/aether-common/src/catalog.rs - Catálogo persistente para DDL con persistencia JSON
//! Soporta CREATE/ALTER/DROP TABLE con tipos SQL básicos y IDENTITY.

use std::collections::HashMap;

pub type TableId = u32;

#[derive(Debug, Clone, PartialEq)]
pub enum DataType {
    Int,
    Float,
    Text,
    Vector(usize), // dim
}

impl DataType {
    pub fn parse(s: &str) -> Option<Self> {
        let up = s.trim().to_uppercase();
        if up == "SERIAL" || up == "BIGSERIAL" || up == "AUTOINCREMENT" || up == "AUTOINCREMENTAL" || up == "AUTO_INCREMENT" { return Some(Self::Int); }
        if up == "INT" || up == "INTEGER" { return Some(Self::Int); }
        if up == "FLOAT" || up == "REAL" || up == "DOUBLE" { return Some(Self::Float); }
        if up == "TEXT" || up == "VARCHAR" || up == "STRING" { return Some(Self::Text); }
        if up.starts_with("VECTOR") {
            if let Some(start) = up.find('(') {
                if let Some(end) = up.find(')') {
                    if let Ok(dim) = up[start+1..end].trim().parse::<usize>() {
                        return Some(Self::Vector(dim));
                    }
                }
            }
            return Some(Self::Vector(768));
        }
        None
    }

    pub fn to_string(&self) -> String {
        match self {
            Self::Int => "INT".into(),
            Self::Float => "FLOAT".into(),
            Self::Text => "TEXT".into(),
            Self::Vector(d) => format!("VECTOR({})", d),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum IdentityKind {
    Always,   // GENERATED ALWAYS AS IDENTITY
    ByDefault, // GENERATED BY DEFAULT AS IDENTITY
}

#[derive(Debug, Clone)]
pub struct IdentitySpec {
    pub kind: IdentityKind,
    pub start: i64,
    pub increment: i64,
}

impl IdentitySpec {
    pub fn new_always() -> Self { Self { kind: IdentityKind::Always, start: 1, increment: 1 } }
    pub fn new_by_default() -> Self { Self { kind: IdentityKind::ByDefault, start: 1, increment: 1 } }
}

#[derive(Debug, Clone)]
pub struct ColumnDef {
    pub name: String,
    pub data_type: DataType,
    pub is_primary_key: bool,
    pub nullable: bool,
    pub identity: Option<IdentitySpec>,
}

impl ColumnDef {
    pub fn new(name: &str, data_type: DataType) -> Self {
        Self { name: name.to_string(), data_type, is_primary_key: false, nullable: true, identity: None }
    }
    pub fn new_identity(name: &str, data_type: DataType, kind: IdentityKind) -> Self {
        Self { name: name.to_string(), data_type, is_primary_key: true, nullable: false, identity: Some(IdentitySpec{ kind, start: 1, increment: 1 }) }
    }
    pub fn is_identity(&self) -> bool { self.identity.is_some() }
    pub fn is_generated_always(&self) -> bool { matches!(&self.identity, Some(s) if s.kind == IdentityKind::Always) }
}

#[derive(Debug, Clone)]
pub struct TableDef {
    pub id: TableId,
    pub name: String,
    pub columns: Vec<ColumnDef>,
}

impl TableDef {
    pub fn column_index(&self, col: &str) -> Option<usize> {
        self.columns.iter().position(|c| c.name.eq_ignore_ascii_case(col))
    }
    pub fn has_column(&self, col: &str) -> bool {
        self.column_index(col).is_some()
    }
}

// Helpers para JSON manual sin serde
fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}
fn json_unescape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(n) = chars.next() {
                match n {
                    '"' => out.push('"'),
                    '\\' => out.push('\\'),
                    'n' => out.push('\n'),
                    'r' => out.push('\r'),
                    't' => out.push('\t'),
                    _ => { out.push('\\'); out.push(n); }
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

#[derive(Debug)]
pub struct Catalog {
    pub tables: HashMap<String, TableDef>, // key lowercased
    next_id: TableId,
    persist_path: Option<String>,
    pub sequences: HashMap<String, i64>, // "table.col" lower -> next_val
}

impl Catalog {
    pub fn new() -> Self {
        Self { tables: HashMap::new(), next_id: 1, persist_path: None, sequences: HashMap::new() }
    }

    pub fn with_persist(path: &str) -> Self {
        let mut c = Self::new();
        c.persist_path = Some(path.to_string());
        // Asegurar directorio padre existe
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        c.load();
        c
    }

    pub fn create_table(&mut self, name: &str, columns: Vec<ColumnDef>) -> Result<TableId, String> {
        let key = name.to_lowercase();
        if self.tables.contains_key(&key) {
            return Err(format!("Table '{}' already exists", name));
        }
        if columns.is_empty() {
            return Err("CREATE TABLE requires at least one column".into());
        }
        let mut seen = std::collections::HashSet::new();
        for col in &columns {
            let lk = col.name.to_lowercase();
            if !seen.insert(lk.clone()) {
                return Err(format!("Duplicate column '{}'", col.name));
            }
        }
        let id = self.next_id;
        self.next_id += 1;
        let def = TableDef { id, name: name.to_string(), columns: columns.clone() };
        self.tables.insert(key.clone(), def);
        // Inicializar secuencias para columnas identity
        for col in &columns {
            if let Some(spec) = &col.identity {
                let seq_key = format!("{}.{}", name.to_lowercase(), col.name.to_lowercase());
                self.sequences.insert(seq_key, spec.start);
            }
        }
        self.persist();
        Ok(id)
    }

    pub fn alter_add_column(&mut self, table: &str, col: ColumnDef) -> Result<(), String> {
        let key = table.to_lowercase();
        let t = self.tables.get_mut(&key).ok_or_else(|| format!("Table '{}' not found", table))?;
        if t.has_column(&col.name) {
            return Err(format!("Column '{}' already exists in '{}'", col.name, table));
        }
        if let Some(spec) = &col.identity {
            let seq_key = format!("{}.{}", table.to_lowercase(), col.name.to_lowercase());
            self.sequences.insert(seq_key, spec.start);
        }
        t.columns.push(col);
        self.persist();
        Ok(())
    }

    pub fn alter_drop_column(&mut self, table: &str, col_name: &str) -> Result<(), String> {
        let key = table.to_lowercase();
        let t = self.tables.get_mut(&key).ok_or_else(|| format!("Table '{}' not found", table))?;
        if t.columns.len() <= 1 {
            return Err("Cannot drop last column".into());
        }
        let idx = t.column_index(col_name).ok_or_else(|| format!("Column '{}' not found", col_name))?;
        if t.columns[idx].is_primary_key {
            return Err(format!("Cannot drop primary key column '{}'", col_name));
        }
        let col_name_owned = t.columns[idx].name.clone();
        t.columns.remove(idx);
        // Eliminar secuencia si era identity
        let seq_key = format!("{}.{}", table.to_lowercase(), col_name_owned.to_lowercase());
        self.sequences.remove(&seq_key);
        self.persist();
        Ok(())
    }

    pub fn drop_table(&mut self, table: &str) -> Result<TableDef, String> {
        let key = table.to_lowercase();
        let def = self.tables.remove(&key).ok_or_else(|| format!("Table '{}' not found", table))?;
        // Eliminar secuencias de esa tabla
        let prefix = format!("{}.", key);
        self.sequences.retain(|k, _| !k.starts_with(&prefix));
        self.persist();
        Ok(def)
    }

    pub fn get_table(&self, table: &str) -> Option<&TableDef> {
        self.tables.get(&table.to_lowercase())
    }

    pub fn list_tables(&self) -> Vec<&TableDef> {
        self.tables.values().collect()
    }

    pub fn get_next_sequence(&mut self, table: &str, col: &str) -> i64 {
        let key = format!("{}.{}", table.to_lowercase(), col.to_lowercase());
        let entry = self.sequences.entry(key.clone()).or_insert(1);
        let val = *entry;
        *entry += 1;
        self.persist();
        val
    }

    pub fn peek_sequence(&self, table: &str, col: &str) -> Option<i64> {
        let key = format!("{}.{}", table.to_lowercase(), col.to_lowercase());
        self.sequences.get(&key).copied()
    }

    pub fn advance_sequence(&mut self, table: &str, col: &str, explicit: i64) {
        let key = format!("{}.{}", table.to_lowercase(), col.to_lowercase());
        let cur = self.sequences.entry(key).or_insert(1);
        if explicit >= *cur {
            *cur = explicit + 1;
            self.persist();
        }
    }

    fn persist(&self) {
        if let Some(path) = &self.persist_path {
            let mut out = String::new();
            out.push_str("{\n");
            out.push_str(&format!("  \"next_id\": {},\n", self.next_id));
            out.push_str("  \"tables\": [\n");
            let mut first_table = true;
            for t in self.tables.values() {
                if !first_table { out.push_str(",\n"); }
                first_table = false;
                out.push_str(&format!("    {{\"id\": {}, \"name\": \"{}\", \"columns\": [", t.id, json_escape(&t.name)));
                let mut first_col = true;
                for c in &t.columns {
                    if !first_col { out.push_str(", "); }
                    first_col = false;
                    let id_json = if let Some(id) = &c.identity {
                        let kind_str = match id.kind {
                            IdentityKind::Always => "Always",
                            IdentityKind::ByDefault => "ByDefault",
                        };
                        format!(", \"identity\": {{\"kind\":\"{}\", \"start\":{}, \"increment\":{}}}", kind_str, id.start, id.increment)
                    } else { "".to_string() };
                    out.push_str(&format!("{{\"name\":\"{}\", \"type\":\"{}\", \"pk\":{}, \"nullable\":{}{}}}", json_escape(&c.name), json_escape(&c.data_type.to_string()), c.is_primary_key, c.nullable, id_json));
                }
                out.push_str("]}");
            }
            out.push_str("\n  ],\n");
            out.push_str("  \"sequences\": {\n");
            let mut first_seq = true;
            for (k, v) in &self.sequences {
                if !first_seq { out.push_str(",\n"); }
                first_seq = false;
                out.push_str(&format!("    \"{}\": {}", json_escape(k), v));
            }
            out.push_str("\n  }\n");
            out.push_str("}\n");
            if let Some(parent) = std::path::Path::new(path).parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let tmp = format!("{}.tmp", path);
            if std::fs::write(&tmp, &out).is_ok() {
                let _ = std::fs::rename(&tmp, path);
                // fsync para durabilidad
                if let Ok(f) = std::fs::OpenOptions::new().read(true).open(path) {
                    let _ = f.sync_all();
                }
            }
        }
    }

    fn load(&mut self) {
        if let Some(path) = &self.persist_path {
            if let Ok(content) = std::fs::read_to_string(path) {
                // Si el archivo es el formato viejo "TABLE ..." intentar migrar, sino parsear JSON
                if content.trim_start().starts_with('{') {
                    self.load_json(&content);
                } else {
                    // Formato viejo: solo contar tablas
                    let count = content.matches("TABLE ").count() as u32;
                    if count > 0 { self.next_id = count + 1; }
                }
            }
        }
    }

    fn load_json(&mut self, content: &str) {
        // Parser JSON muy simple y tolerante, sin serde, solo para nuestro formato
        // Extraer next_id
        if let Some(p) = content.find("\"next_id\"") {
            if let Some(colon) = content[p..].find(':') {
                let after = &content[p+colon+1..];
                let num_str: String = after.chars().skip_while(|c| c.is_whitespace()).take_while(|c| c.is_ascii_digit()).collect();
                if let Ok(n) = num_str.parse::<u32>() { self.next_id = n; }
            }
        }
        // Extraer tables array: buscar "tables": [
        if let Some(tables_start) = content.find("\"tables\"") {
            if let Some(bracket) = content[tables_start..].find('[') {
                let tables_content_start = tables_start + bracket + 1;
                // Encontrar cierre del array tables: buscar "],\n  \"sequences\""
                let mut tables_json = String::new();
                if let Some(seq_pos) = content[tables_content_start..].find("\"sequences\"") {
                    // El array termina antes de ,"sequences"
                    let before_seq = &content[tables_content_start..tables_start + seq_pos + content[tables_start..].find("\"sequences\"").unwrap_or(0)];
                    // Simplificado: extraer entre [ y ] que corresponde a tables
                    // Buscar el último "]" antes de "\"sequences\""
                    if let Some(last_bracket) = content[..content.find("\"sequences\"").unwrap_or(content.len())].rfind(']') {
                        if last_bracket > tables_content_start {
                            tables_json = content[tables_content_start..last_bracket].to_string();
                        }
                    }
                }
                // Parsear cada tabla: buscar {"id":, "name":, "columns": [ ... ] }
                let mut pos = 0;
                while let Some(id_pos) = tables_json[pos..].find("\"id\"") {
                    let abs_id_pos = pos + id_pos;
                    // Extraer id
                    let id_start = tables_json[abs_id_pos..].find(':').map(|v| abs_id_pos + v + 1).unwrap_or(abs_id_pos);
                    let id_str: String = tables_json[id_start..].chars().skip_while(|c| c.is_whitespace()).take_while(|c| c.is_ascii_digit()).collect();
                    let table_id: u32 = id_str.parse().unwrap_or(1);
                    // Extraer name
                    let name_pos = tables_json[abs_id_pos..].find("\"name\"").map(|v| abs_id_pos + v).unwrap_or(abs_id_pos);
                    let name_colon = tables_json[name_pos..].find(':').map(|v| name_pos + v).unwrap_or(name_pos);
                    let name_quote_start = tables_json[name_colon..].find('"').map(|v| name_colon + v + 1).unwrap_or(name_colon);
                    let name_quote_end = tables_json[name_quote_start..].find('"').map(|v| name_quote_start + v).unwrap_or(name_quote_start);
                    let table_name = json_unescape(&tables_json[name_quote_start..name_quote_end]);
                    // Extraer columns array
                    let cols_pos = tables_json[name_quote_end..].find("\"columns\"").map(|v| name_quote_end + v).unwrap_or(name_quote_end);
                    let cols_bracket = tables_json[cols_pos..].find('[').map(|v| cols_pos + v).unwrap_or(cols_pos);
                    // Encontrar cierre de columns: buscar "]" correspondiente
                    let mut depth = 0;
                    let mut cols_end = cols_bracket;
                    for (i, c) in tables_json[cols_bracket..].char_indices() {
                        if c == '[' { depth += 1; }
                        if c == ']' { depth -= 1; if depth == 0 { cols_end = cols_bracket + i; break; } }
                    }
                    let cols_json = &tables_json[cols_bracket+1..cols_end];
                    let mut columns: Vec<ColumnDef> = Vec::new();
                    // Parsear cada columna: {"name":"...", "type":"...", "pk":..., "nullable":..., "identity":{...}}
                    let mut cpos = 0;
                    while let Some(name_p) = cols_json[cpos..].find("\"name\"") {
                        let abs = cpos + name_p;
                        let colon = cols_json[abs..].find(':').map(|v| abs + v).unwrap_or(abs);
                        let qs = cols_json[colon..].find('"').map(|v| colon + v + 1).unwrap_or(colon);
                        let qe = cols_json[qs..].find('"').map(|v| qs + v).unwrap_or(qs);
                        let col_name = json_unescape(&cols_json[qs..qe]);
                        // type
                        let type_p = cols_json[qe..].find("\"type\"").map(|v| qe + v).unwrap_or(qe);
                        let type_colon = cols_json[type_p..].find(':').map(|v| type_p + v).unwrap_or(type_p);
                        let type_qs = cols_json[type_colon..].find('"').map(|v| type_colon + v + 1).unwrap_or(type_colon);
                        let type_qe = cols_json[type_qs..].find('"').map(|v| type_qs + v).unwrap_or(type_qs);
                        let type_str = json_unescape(&cols_json[type_qs..type_qe]);
                        let dt = DataType::parse(&type_str).unwrap_or(DataType::Text);
                        // pk
                        let pk_p = cols_json[type_qe..].find("\"pk\"").map(|v| type_qe + v).unwrap_or(type_qe);
                        let pk_colon = cols_json[pk_p..].find(':').map(|v| pk_p + v).unwrap_or(pk_p);
                        let pk_val_start = cols_json[pk_colon+1..].trim_start();
                        let is_pk = pk_val_start.starts_with("true");
                        // nullable
                        let null_p = cols_json[pk_colon..].find("\"nullable\"").map(|v| pk_colon + v).unwrap_or(pk_colon);
                        let null_colon = cols_json[null_p..].find(':').map(|v| null_p + v).unwrap_or(null_p);
                        let null_val = cols_json[null_colon+1..].trim_start();
                        let is_nullable = null_val.starts_with("true");
                        // identity (opcional)
                        let mut identity = None;
                        // Buscar "identity" entre type_qe y próximo "name" o fin
                        let next_name = cols_json[qe..].find("\"name\"").map(|v| qe + v).unwrap_or(cols_json.len());
                        let search_slice = &cols_json[qe..next_name.min(cols_json.len())];
                        if let Some(id_pos) = search_slice.find("\"identity\"") {
                            let id_abs = qe + id_pos;
                            // kind
                            if let Some(kind_pos) = cols_json[id_abs..].find("\"kind\"") {
                                let kind_colon = cols_json[kind_pos+id_abs..].find(':').map(|v| id_abs + kind_pos + v).unwrap_or(id_abs);
                                let kind_qs = cols_json[kind_colon..].find('"').map(|v| kind_colon + v + 1).unwrap_or(kind_colon);
                                let kind_qe = cols_json[kind_qs..].find('"').map(|v| kind_qs + v).unwrap_or(kind_qs);
                                let kind_str = &cols_json[kind_qs..kind_qe];
                                let kind = if kind_str == "Always" { IdentityKind::Always } else { IdentityKind::ByDefault };
                                // start
                                let start_pos = cols_json[kind_qe..].find("\"start\"").map(|v| kind_qe + v).unwrap_or(kind_qe);
                                let start_colon = cols_json[start_pos..].find(':').map(|v| start_pos + v).unwrap_or(start_pos);
                                let start_num: String = cols_json[start_colon+1..].chars().skip_while(|c| c.is_whitespace()).take_while(|c| c.is_ascii_digit() || *c=='-').collect();
                                let start_val: i64 = start_num.parse().unwrap_or(1);
                                let inc_pos = cols_json[start_colon..].find("\"increment\"").map(|v| start_colon + v).unwrap_or(start_colon);
                                let inc_colon = cols_json[inc_pos..].find(':').map(|v| inc_pos + v).unwrap_or(inc_pos);
                                let inc_num: String = cols_json[inc_colon+1..].chars().skip_while(|c| c.is_whitespace()).take_while(|c| c.is_ascii_digit() || *c=='-').collect();
                                let inc_val: i64 = inc_num.parse().unwrap_or(1);
                                identity = Some(IdentitySpec{ kind, start: start_val, increment: inc_val });
                            }
                        }
                        let mut col = ColumnDef::new(&col_name, dt);
                        col.is_primary_key = is_pk;
                        col.nullable = is_nullable;
                        col.identity = identity;
                        columns.push(col);
                        // Avanzar cpos
                        if let Some(next) = cols_json[qe..].find("\"name\"") {
                            if qe + next <= cpos { cpos = qe + 1; } else { cpos = qe + next; }
                            // Evitar bucle infinito: si no avanzamos, salir
                            if cpos <= abs { cpos = abs + 10; }
                        } else { break; }
                        if cpos >= cols_json.len() { break; }
                        // Si ya procesamos todos, salir
                        if columns.len() > 100 { break; }
                        // Buscar próxima columna: si no hay más "name" después de qe, salir
                        if cols_json[cpos..].find("\"name\"").is_none() { break; }
                    }
                    let table_def = TableDef{ id: table_id, name: table_name.clone(), columns };
                    self.tables.insert(table_name.to_lowercase(), table_def);
                    if table_id >= self.next_id { self.next_id = table_id + 1; }
                    pos = abs_id_pos + 10;
                    if pos >= tables_json.len() { break; }
                    // Evitar bucle infinito
                    if tables_json[pos..].find("\"id\"").is_none() { break; }
                }
                // Parsear sequences
                if let Some(seq_start) = content.find("\"sequences\"") {
                    if let Some(b) = content[seq_start..].find('{') {
                        let seq_content_start = seq_start + b + 1;
                        if let Some(end) = content[seq_content_start..].find('}') {
                            let seq_json = &content[seq_content_start..seq_content_start+end];
                            for pair in seq_json.split(',') {
                                let pair = pair.trim();
                                if pair.is_empty() { continue; }
                                if let Some(colon) = pair.find(':') {
                                    let key_raw = pair[..colon].trim().trim_matches('"');
                                    let key = json_unescape(key_raw);
                                    let val_str = pair[colon+1..].trim();
                                    if let Ok(v) = val_str.parse::<i64>() {
                                        self.sequences.insert(key, v);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_create_alter_drop() {
        let mut cat = Catalog::new();
        let cols = vec![
            ColumnDef::new("id", DataType::Int),
            ColumnDef::new("nombre", DataType::Text),
        ];
        assert!(cat.create_table("productos", cols).is_ok());
        assert!(cat.create_table("productos", vec![ColumnDef::new("x", DataType::Int)]).is_err());
        assert!(cat.alter_add_column("productos", ColumnDef::new("precio", DataType::Float)).is_ok());
        assert!(cat.alter_drop_column("productos", "precio").is_ok());
        assert!(cat.alter_drop_column("productos", "noexiste").is_err());
        assert!(cat.drop_table("productos").is_ok());
        assert!(cat.get_table("productos").is_none());
    }

    #[test]
    fn catalog_persist_identity() {
        let path = std::env::temp_dir().join("test_catalog_persist.json");
        let _ = std::fs::remove_file(&path);
        let mut cat = Catalog::with_persist(path.to_str().unwrap());
        let mut col_id = ColumnDef::new("id", DataType::Int);
        col_id.is_primary_key = true;
        col_id.nullable = false;
        col_id.identity = Some(IdentitySpec::new_always());
        cat.create_table("t", vec![col_id, ColumnDef::new("nombre", DataType::Text)]).unwrap();
        cat.get_next_sequence("t", "id");
        drop(cat);
        let cat2 = Catalog::with_persist(path.to_str().unwrap());
        assert!(cat2.get_table("t").is_some());
        let tbl = cat2.get_table("t").unwrap();
        assert!(tbl.columns[0].is_identity());
        assert_eq!(tbl.columns[0].name, "id");
        assert_eq!(cat2.peek_sequence("t", "id"), Some(2));
        let _ = std::fs::remove_file(&path);
    }
}
