//! crates/argentum-common/src/catalog.rs - Catálogo persistente para DDL con persistencia JSON
//! Soporta CREATE/ALTER/DROP TABLE con tipos SQL básicos y IDENTITY.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub type TableId = u32;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(into = "String", from = "String")]
pub enum DataType {
    Int,
    Float,
    Text,
    Vector(usize), // dim
}

impl From<DataType> for String {
    fn from(dt: DataType) -> String { dt.to_string() }
}

impl From<String> for DataType {
    fn from(s: String) -> Self {
        DataType::parse(&s).unwrap_or(DataType::Text)
    }
}

impl DataType {
    pub fn parse(s: &str) -> Option<Self> {
        let up = s.trim().to_uppercase();
        if up == "SERIAL" || up == "BIGSERIAL" || up == "AUTOINCREMENT" || up == "AUTOINCREMENTAL" || up == "AUTO_INCREMENT" { return Some(Self::Int); }
        if up == "INT" || up == "INTEGER" { return Some(Self::Int); }
        if up == "FLOAT" || up == "REAL" || up == "DOUBLE" { return Some(Self::Float); }
        if up == "TEXT" || up == "VARCHAR" || up == "STRING" { return Some(Self::Text); }
        if up.starts_with("VECTOR") {
            if let Some(start) = up.find('(') {
                if let Some(end) = up.find(')') {
                    if let Ok(dim) = up[start+1..end].trim().parse::<usize>() {
                        return Some(Self::Vector(dim));
                    }
                }
            }
            return Some(Self::Vector(768));
        }
        None
    }

    pub fn to_string(&self) -> String {
        match self {
            Self::Int => "INT".into(),
            Self::Float => "FLOAT".into(),
            Self::Text => "TEXT".into(),
            Self::Vector(d) => format!("VECTOR({})", d),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum IdentityKind {
    Always,   // GENERATED ALWAYS AS IDENTITY
    ByDefault, // GENERATED BY DEFAULT AS IDENTITY
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdentitySpec {
    pub kind: IdentityKind,
    pub start: i64,
    pub increment: i64,
}

impl IdentitySpec {
    pub fn new_always() -> Self { Self { kind: IdentityKind::Always, start: 1, increment: 1 } }
    pub fn new_by_default() -> Self { Self { kind: IdentityKind::ByDefault, start: 1, increment: 1 } }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnDef {
    pub name: String,
    #[serde(alias = "type")]
    pub data_type: DataType,
    #[serde(alias = "pk")]
    pub is_primary_key: bool,
    pub nullable: bool,
    pub identity: Option<IdentitySpec>,
}

impl ColumnDef {
    pub fn new(name: &str, data_type: DataType) -> Self {
        Self { name: name.to_string(), data_type, is_primary_key: false, nullable: true, identity: None }
    }
    pub fn new_identity(name: &str, data_type: DataType, kind: IdentityKind) -> Self {
        Self { name: name.to_string(), data_type, is_primary_key: true, nullable: false, identity: Some(IdentitySpec{ kind, start: 1, increment: 1 }) }
    }
    pub fn is_identity(&self) -> bool { self.identity.is_some() }
    pub fn is_generated_always(&self) -> bool { matches!(&self.identity, Some(s) if s.kind == IdentityKind::Always) }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableDef {
    pub id: TableId,
    pub name: String,
    pub columns: Vec<ColumnDef>,
}

impl TableDef {
    pub fn column_index(&self, col: &str) -> Option<usize> {
        self.columns.iter().position(|c| c.name.eq_ignore_ascii_case(col))
    }
    pub fn has_column(&self, col: &str) -> bool {
        self.column_index(col).is_some()
    }
}

// (Sin helpers JSON manuales: serde_json maneja el escape correctamente.)

#[derive(Debug)]
pub struct Catalog {
    pub tables: HashMap<String, TableDef>, // key lowercased
    next_id: TableId,
    persist_path: Option<String>,
    pub sequences: HashMap<String, i64>, // "table.col" lower -> next_val
}

impl Catalog {
    pub fn new() -> Self {
        Self { tables: HashMap::new(), next_id: 1, persist_path: None, sequences: HashMap::new() }
    }

    pub fn with_persist(path: &str) -> Self {
        let mut c = Self::new();
        c.persist_path = Some(path.to_string());
        // Asegurar directorio padre existe
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        c.load();
        c
    }

    pub fn create_table(&mut self, name: &str, columns: Vec<ColumnDef>) -> Result<TableId, String> {
        let key = name.to_lowercase();
        if self.tables.contains_key(&key) {
            return Err(format!("Table '{}' already exists", name));
        }
        if columns.is_empty() {
            return Err("CREATE TABLE requires at least one column".into());
        }
        let mut seen = std::collections::HashSet::new();
        for col in &columns {
            let lk = col.name.to_lowercase();
            if !seen.insert(lk.clone()) {
                return Err(format!("Duplicate column '{}'", col.name));
            }
        }
        let id = self.next_id;
        self.next_id += 1;
        let def = TableDef { id, name: name.to_string(), columns: columns.clone() };
        self.tables.insert(key.clone(), def);
        // Inicializar secuencias para columnas identity
        for col in &columns {
            if let Some(spec) = &col.identity {
                let seq_key = format!("{}.{}", name.to_lowercase(), col.name.to_lowercase());
                self.sequences.insert(seq_key, spec.start);
            }
        }
        self.persist();
        Ok(id)
    }

    pub fn alter_add_column(&mut self, table: &str, col: ColumnDef) -> Result<(), String> {
        let key = table.to_lowercase();
        let t = self.tables.get_mut(&key).ok_or_else(|| format!("Table '{}' not found", table))?;
        if t.has_column(&col.name) {
            return Err(format!("Column '{}' already exists in '{}'", col.name, table));
        }
        if let Some(spec) = &col.identity {
            let seq_key = format!("{}.{}", table.to_lowercase(), col.name.to_lowercase());
            self.sequences.insert(seq_key, spec.start);
        }
        t.columns.push(col);
        self.persist();
        Ok(())
    }

    pub fn alter_drop_column(&mut self, table: &str, col_name: &str) -> Result<(), String> {
        let key = table.to_lowercase();
        let t = self.tables.get_mut(&key).ok_or_else(|| format!("Table '{}' not found", table))?;
        if t.columns.len() <= 1 {
            return Err("Cannot drop last column".into());
        }
        let idx = t.column_index(col_name).ok_or_else(|| format!("Column '{}' not found", col_name))?;
        if t.columns[idx].is_primary_key {
            return Err(format!("Cannot drop primary key column '{}'", col_name));
        }
        let col_name_owned = t.columns[idx].name.clone();
        t.columns.remove(idx);
        // Eliminar secuencia si era identity
        let seq_key = format!("{}.{}", table.to_lowercase(), col_name_owned.to_lowercase());
        self.sequences.remove(&seq_key);
        self.persist();
        Ok(())
    }

    pub fn drop_table(&mut self, table: &str) -> Result<TableDef, String> {
        let key = table.to_lowercase();
        let def = self.tables.remove(&key).ok_or_else(|| format!("Table '{}' not found", table))?;
        // Eliminar secuencias de esa tabla
        let prefix = format!("{}.", key);
        self.sequences.retain(|k, _| !k.starts_with(&prefix));
        self.persist();
        Ok(def)
    }

    pub fn get_table(&self, table: &str) -> Option<&TableDef> {
        self.tables.get(&table.to_lowercase())
    }

    pub fn list_tables(&self) -> Vec<&TableDef> {
        self.tables.values().collect()
    }

    pub fn get_next_sequence(&mut self, table: &str, col: &str) -> i64 {
        let key = format!("{}.{}", table.to_lowercase(), col.to_lowercase());
        let entry = self.sequences.entry(key.clone()).or_insert(1);
        let val = *entry;
        *entry += 1;
        self.persist();
        val
    }

    pub fn peek_sequence(&self, table: &str, col: &str) -> Option<i64> {
        let key = format!("{}.{}", table.to_lowercase(), col.to_lowercase());
        self.sequences.get(&key).copied()
    }

    pub fn advance_sequence(&mut self, table: &str, col: &str, explicit: i64) {
        let key = format!("{}.{}", table.to_lowercase(), col.to_lowercase());
        let cur = self.sequences.entry(key).or_insert(1);
        if explicit >= *cur {
            *cur = explicit + 1;
            self.persist();
        }
    }

    pub fn persist(&self) {
        if let Some(path) = &self.persist_path {
            // Snapshot serializable: contiene el next_id global, las tablas y las
            // secuencias. Mantenemos la misma forma JSON que el parser manual viejo
            // emitía, para no invalidar catálogos ya guardados en disco.
            #[derive(Serialize)]
            struct CatalogSnapshot<'a> {
                next_id: TableId,
                tables: Vec<&'a TableDef>,
                sequences: BTreeMap<&'a String, &'a i64>,
            }
            // BTreeMap para que las secuencias se serialicen ordenadas (estable
            // entre ejecuciones -> diffs de tests más limpios).
            use std::collections::BTreeMap;
            let tables_vec: Vec<&TableDef> = self.tables.values().collect();
            let seqs: BTreeMap<&String, &i64> = self.sequences.iter().collect();
            let snap = CatalogSnapshot {
                next_id: self.next_id,
                tables: tables_vec,
                sequences: seqs,
            };
            let out = match serde_json::to_string_pretty(&snap) {
                Ok(s) => s,
                Err(e) => {
                    eprintln!("argentum: catalog persist serialize error: {}", e);
                    return;
                }
            };
            if let Some(parent) = std::path::Path::new(path).parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            // Atomic write: tmp + rename + fsync.
            let tmp = format!("{}.tmp", path);
            if std::fs::write(&tmp, out.as_bytes()).is_ok() {
                if std::fs::rename(&tmp, path).is_ok() {
                    if let Ok(f) = std::fs::OpenOptions::new().read(true).open(path) {
                        let _ = f.sync_all();
                    }
                }
            }
        }
    }

    fn load(&mut self) {
        let Some(path) = self.persist_path.clone() else { return; };
        let Ok(content) = std::fs::read_to_string(&path) else { return; };
        // Forma vieja no-JSON: "TABLE ..." (un nombre por línea).
        if !content.trim_start().starts_with('{') {
            let count = content.matches("TABLE ").count() as TableId;
            if count > 0 { self.next_id = count + 1; }
            return;
        }
        // Forma JSON actual. serde_json nos da un error tipado si está malformado;
        // no hacemos panic, degradamos a catálogo vacío (la base queda con
        // `tables: []` y `sequences: {}` y al primer DDL se reescribe limpio).
        #[derive(Deserialize)]
        struct CatalogSnapshot {
            #[serde(default = "default_next_id")]
            next_id: TableId,
            #[serde(default)]
            tables: Vec<TableDef>,
            #[serde(default)]
            sequences: HashMap<String, i64>,
        }
        fn default_next_id() -> TableId { 1 }

        match serde_json::from_str::<CatalogSnapshot>(&content) {
            Ok(snap) => {
                self.next_id = snap.next_id;
                for t in snap.tables {
                    self.tables.insert(t.name.to_lowercase(), t);
                }
                self.sequences = snap.sequences;
            }
            Err(e) => {
                eprintln!("argentum: catalog load JSON error in '{}': {} -> degradando a catálogo vacío", path, e);
                self.next_id = 1;
                self.tables.clear();
                self.sequences.clear();
            }
        }
    }

    // (El parser manual de JSON fue reemplazado por serde_json en load arriba.)
}
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_create_alter_drop() {
        let mut cat = Catalog::new();
        let cols = vec![
            ColumnDef::new("id", DataType::Int),
            ColumnDef::new("nombre", DataType::Text),
        ];
        assert!(cat.create_table("productos", cols).is_ok());
        assert!(cat.create_table("productos", vec![ColumnDef::new("x", DataType::Int)]).is_err());
        assert!(cat.alter_add_column("productos", ColumnDef::new("precio", DataType::Float)).is_ok());
        assert!(cat.alter_drop_column("productos", "precio").is_ok());
        assert!(cat.alter_drop_column("productos", "noexiste").is_err());
        assert!(cat.drop_table("productos").is_ok());
        assert!(cat.get_table("productos").is_none());
    }

    #[test]
    fn catalog_persist_identity() {
        let path = std::env::temp_dir().join("test_catalog_persist.json");
        let _ = std::fs::remove_file(&path);
        let mut cat = Catalog::with_persist(path.to_str().unwrap());
        let mut col_id = ColumnDef::new("id", DataType::Int);
        col_id.is_primary_key = true;
        col_id.nullable = false;
        col_id.identity = Some(IdentitySpec::new_always());
        cat.create_table("t", vec![col_id, ColumnDef::new("nombre", DataType::Text)]).unwrap();
        cat.get_next_sequence("t", "id");
        drop(cat);
        let cat2 = Catalog::with_persist(path.to_str().unwrap());
        assert!(cat2.get_table("t").is_some());
        let tbl = cat2.get_table("t").unwrap();
        assert!(tbl.columns[0].is_identity());
        assert_eq!(tbl.columns[0].name, "id");
        assert_eq!(cat2.peek_sequence("t", "id"), Some(2));
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn catalog_persist_multi_table_and_sequences() {
        // Crea dos tablas con varias secuencias y verifica que tras persistir
        // y recargar, TODO vuelve intacto: nombres, tipos, identity, sequences.
        let path = std::env::temp_dir().join("test_catalog_multi.json");
        let _ = std::fs::remove_file(&path);
        let path_str = path.to_str().unwrap().to_string();

        // Sesión 1: poblar
        {
            let mut cat = Catalog::with_persist(&path_str);
            // Tabla A con identity ALWAYS
            let mut id_a = ColumnDef::new("id", DataType::Int);
            id_a.is_primary_key = true;
            id_a.nullable = false;
            id_a.identity = Some(IdentitySpec::new_always());
            cat.create_table("tabla_a", vec![id_a, ColumnDef::new("v", DataType::Float)]).unwrap();
            // Tabla B con identity BY DEFAULT + columna Vector(384)
            let mut id_b = ColumnDef::new("id", DataType::Int);
            id_b.identity = Some(IdentitySpec::new_by_default());
            id_b.is_primary_key = true;
            id_b.nullable = false;
            cat.create_table("tabla_b", vec![
                id_b,
                ColumnDef::new("desc", DataType::Text),
                ColumnDef::new("vec", DataType::Vector(384)),
            ]).unwrap();
            // Avanzar sequences
            cat.get_next_sequence("tabla_a", "id");
            cat.get_next_sequence("tabla_a", "id");
            cat.get_next_sequence("tabla_a", "id");
            cat.get_next_sequence("tabla_b", "id");
            cat.get_next_sequence("tabla_b", "id");
        }

        // Sesión 2: verificar
        let cat2 = Catalog::with_persist(&path_str);
        // Tabla A
        let ta = cat2.get_table("tabla_a").expect("tabla_a debe existir");
        assert_eq!(ta.name, "tabla_a");
        assert_eq!(ta.columns.len(), 2);
        assert_eq!(ta.columns[0].name, "id");
        assert!(ta.columns[0].is_identity());
        assert!(ta.columns[0].is_generated_always());
        assert_eq!(ta.columns[1].data_type, DataType::Float);
        // Tabla B
        let tb = cat2.get_table("tabla_b").expect("tabla_b debe existir");
        assert_eq!(tb.columns.len(), 3);
        assert!(tb.columns[0].is_identity());
        assert!(!tb.columns[0].is_generated_always()); // ByDefault
        assert_eq!(tb.columns[2].data_type, DataType::Vector(384));
        // Secuencias
        assert_eq!(cat2.peek_sequence("tabla_a", "id"), Some(4)); // 1,2,3 next=4
        assert_eq!(cat2.peek_sequence("tabla_b", "id"), Some(3)); // 1,2 next=3
        // next_id global
        assert!(cat2.next_id >= 3);

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn catalog_load_backward_compat_with_old_format() {
        // Escribe un catalog con el formato manual viejo (el que producía el
        // parser JSON hand-rolled) y verifica que el nuevo loader con serde_json
        // lo lee correctamente. Esto garantiza que bases pre-existentes en disco
        // no quedan huérfanas tras el upgrade.
        let path = std::env::temp_dir().join("test_catalog_legacy.json");
        let _ = std::fs::remove_file(&path);
        let legacy = r#"{
  "next_id": 5,
  "tables": [
    {"id": 1, "name": "users", "columns": [{"name":"id", "type":"INT", "pk":true, "nullable":false, "identity":{"kind":"Always", "start":1, "increment":1}}, {"name":"name", "type":"TEXT", "pk":false, "nullable":true}]},
    {"id": 2, "name": "orders", "columns": [{"name":"id", "type":"INT", "pk":true, "nullable":false, "identity":{"kind":"ByDefault", "start":100, "increment":2}}, {"name":"total", "type":"FLOAT", "pk":false, "nullable":true}]}
  ],
  "sequences": {
    "users.id": 42,
    "orders.id": 200
  }
}
"#;
        std::fs::write(&path, legacy).unwrap();
        let cat = Catalog::with_persist(path.to_str().unwrap());
        // Tablas
        assert!(cat.get_table("users").is_some());
        assert!(cat.get_table("orders").is_some());
        let users = cat.get_table("users").unwrap();
        assert_eq!(users.columns.len(), 2);
        assert!(users.columns[0].is_identity());
        assert!(users.columns[0].is_generated_always());
        assert_eq!(users.columns[1].data_type, DataType::Text);
        let orders = cat.get_table("orders").unwrap();
        assert!(orders.columns[0].is_identity());
        assert!(!orders.columns[0].is_generated_always());
        assert_eq!(orders.columns[1].data_type, DataType::Float);
        // Secuencias
        assert_eq!(cat.peek_sequence("users", "id"), Some(42));
        assert_eq!(cat.peek_sequence("orders", "id"), Some(200));
        // next_id
        assert_eq!(cat.next_id, 5);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn catalog_load_corrupt_json_degrades_gracefully() {
        // Si el catalog.json está corrupto, NO debe panicar: debe degradarse
        // a catálogo vacío y al primer DDL se reescribe limpio.
        let path = std::env::temp_dir().join("test_catalog_corrupt.json");
        let _ = std::fs::remove_file(&path);
        std::fs::write(&path, b"{ esto no es json valido \xFF\xFE malformed >>>").unwrap();
        let mut cat = Catalog::with_persist(path.to_str().unwrap());
        // Catálogo vacío
        assert!(cat.get_table("cualquiera").is_none());
        assert!(cat.peek_sequence("cualquiera", "x").is_none());
        // Y debe poder seguir trabajando: crear una tabla reescribe el JSON limpio
        cat.create_table("nueva", vec![ColumnDef::new("id", DataType::Int)]).unwrap();
        let cat2 = Catalog::with_persist(path.to_str().unwrap());
        assert!(cat2.get_table("nueva").is_some());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn catalog_persist_is_atomic_no_tmp_left_on_success() {
        // Tras un persist exitoso, no debe quedar archivo .tmp colgando.
        let path = std::env::temp_dir().join("test_catalog_atomic.json");
        let _ = std::fs::remove_file(&path);
        let tmp = format!("{}.tmp", path.to_str().unwrap());
        let _ = std::fs::remove_file(&tmp);
        let mut cat = Catalog::with_persist(path.to_str().unwrap());
        cat.create_table("atomica", vec![ColumnDef::new("id", DataType::Int)]).unwrap();
        // El .tmp fue renombrado, no debe existir
        assert!(!std::path::Path::new(&tmp).exists(), "el .tmp no debe quedar");
        // El catalog final debe existir y ser JSON parseable
        let content = std::fs::read_to_string(&path).unwrap();
        let v: serde_json::Value = serde_json::from_str(&content).unwrap();
        assert_eq!(v["tables"].as_array().unwrap().len(), 1);
        let _ = std::fs::remove_file(&path);
    }
}
